[package]
name = "ds18b20"
version = "0.1.0"
edition = "2021"

[dependencies]
one-wire-bus = "0.1.1"
modular-bitfield = "0.11.2"
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal.git" }
fugit = "0.3.5"